spring.application.name=cowork

# Aquí se configura la conexión con la base de datos PostgreSQL.
spring.datasource.url=jdbc:postgresql://localhost:5432/cowork

# Aquí se toman las credenciales desde variables de entorno.
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Aquí se indica el driver de PostgreSQL.
spring.datasource.driver-class-name=org.postgresql.Driver

# Aquí se permite que Hibernate cree o actualice las tablas según las entidades.
spring.jpa.hibernate.ddl-auto=update

# Aquí se muestra en consola el SQL generado por Hibernate.
spring.jpa.show-sql=true

# Aquí se mejora la lectura del SQL mostrado en consola.
spring.jpa.properties.hibernate.format_sql=true
